config/routes.rb
Ringtack::Application.routes.draw do

  authenticated :user do
    root :to => 'static_pages#home'
  end

  root :to => 'static_pages#home'

  devise_for :users
  
  resources :rings do
    resources :posts
  end
  
  
  resources :ring_sessions, only: [:create]
  
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
    
  end
  
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  attr_accessible :category_id, :ring_id, :category
  belongs_to :ring
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :categorizations
  has_many :rings, :through => :categorizations
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :ring
  belongs_to :user
  attr_accessible :content, :user_id
end

app/models/ring.rb
class Ring < ActiveRecord::Base 
  attr_accessible :name, :categorizations_attributes, :categories, :size, :latitude, :longitude
  has_many :posts, dependent: :destroy
  has_many :categorizations
  has_many :categories, :through => :categorizations
  accepts_nested_attributes_for :categorizations
  
  geocoded_by :location
  after_validation :geocode
  
  after_create :save_categories
  
  def location
    location = "#{self.latitude}, #{self.longitude}"
  end
  
  
  def self.inside(lat, lon)
    near([lat, lon], 20).select {|i| (i.size * 0.5) >= i.distance_from([lat,lon])}
  end
  
  def categories=(attributes)
    category = Category.find_or_create_by_name(attributes[:name])
    categorizations.new(:category => category)
  end
  
  def save_categories
    categorizations.each(&:save!)
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
	extend Rolify
	rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :title, :body
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
  
  def create
     @ring = Ring.find(params[:ring_id])
     @post = @ring.posts.create(params[:post].merge(:user_id => current_user.id))
     redirect_to ring_path(@ring)
  end
  
end

app/controllers/ring_sessions_controller.rb
class RingSessionsController < ApplicationController

  def create
    if @insiderings = Ring.inside(params[:latitude], params[:longitude])
      session[:ring_session] = @insiderings.map(&:id).join(",")
      redirect_to rings_path

    end
  end
  
end

app/controllers/rings_controller.rb
class RingsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @rings = Ring.all
    @inrings = Ring.find(session[:ring_session].split(","))
  end

  def new
    @ring = Ring.new
  end

  def show
    @ring = Ring.find(params[:id])
  end

  def create
    @ring = Ring.new(params[:ring])

    if @ring.save
      redirect_to(@ring, :notice => 'Ring created!')
    else
      render :action => "new"
    end
  end

  def edit
    authorize! :edit, @ring, :notice => 'You are not authorized to perform this action'
    @ring = Ring.find(params[:id])  
  end

  def update
    @ring = Ring.find(params[:id])

    if @ring.update_attributes(params[:ring])
      redirect_to @ring, :notice => 'Ring updated successfully.'
    else
      render "edit" 
    end
  end

  def destroy
    @ring = Ring.find(params[:id])
    @ring.destroy

     respond_to do |format|
       format.html { redirect_to rings_url }
     end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/ring_sessions_helper.rb
module RingSessionsHelper
end

app/helpers/rings_helper.rb
module RingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ringtack</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= yield :javascripts %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Ringtack", root_path , id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home", root_path %></li>
			  <% if user_signed_in? %>
			  <li>
			  <%= link_to 'Rings', rings_path %>
			  </li>
			  <li>
			  <%= link_to('Sign out', destroy_user_session_path, :method => :delete) %>        
			  </li>
			  <% else %>
			  <li>
			  <%= link_to('Sign in', new_user_session_path)  %>  
			  </li>
			  <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/ring_sessions/_form.html.erb
<%= form_for(:session, url: ring_sessions_path) do |f| %>

<div class="field">
	<%= f.label :latitude %>
	<%= f.text_field :latitude%>
	<%= f.label :longitude %>
	<%= f.text_field :longitude%>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/ring_sessions/destroy.html.erb
<h1>RingSessions#destroy</h1>
<p>Find me in app/views/ring_sessions/destroy.html.erb</p>

app/views/ring_sessions/new.html.erb
<% content_for :javascripts do %>
   <%= javascript_include_tag "geolocation" %>
<% end %>

<h1>RingSessions#new</h1>
<%= render 'form' %>

<%= @session %>

app/views/rings/_form.html.erb
<%= form_for(@ring) do |f| %>
  <% if @ring.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@ring.errors.count, "error") %> prohibited
    	this ring from being saved:</h2>
	<ul>
	<% @ring.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
	<% end %>
	</ul>
  </div>
  <% end %>
 
  <div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
  </div>
  <div class="field">
	<%= f.fields_for :categories do |builder| %>
	  <%= builder.label :name, "Category" %><br />
	  <%= builder.text_field :name %>
	<% end %>
  </div>
  <div class="field">
	<%= f.label :size %><br />
	<%= f.text_field :size %>
  </div>  
  <div class="field">
	<%= f.hidden_field :latitude%>
	<%= f.hidden_field :longitude%>
  </div>
  <div class="actions">
	<%= f.submit %>
  </div>
<% end %>

app/views/rings/edit.html.erb
<h1>Update Ring</h1>
 
<%= render 'form' %>

app/views/rings/index.html.erb
<% content_for :javascripts do %>
   <%= javascript_include_tag "geolocation" %>
<% end %>

<h1>Rings</h1>
 
<table>
  <tr>
    <th>Name</th>
  </tr>
<% @inrings.each do |ring| %>
  <tr>
    <td><%= link_to ring.name, ring %></td>
	<td><%= ring.latitude %></td>
	<td><%= ring.longitude %></td>
	<td><%= image_tag	"http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{ring.latitude}%2C#{ring.longitude}"%></td>
    <% if can? :update, @ring %>
	<td><%= link_to "Edit", edit_ring_path(ring) %>
	<td><%= link_to "Destroy", @ring, :method => :delete, :confirm => "Are you sure?" %>
	<% end %>   
  </tr>
<% end %>
</table>
<br />

<br />
 
<%= link_to 'Create a Ring', new_ring_path %>

<br />

app/views/rings/new.html.erb
<% content_for :javascripts do %>
   <%= javascript_include_tag "geolocation" %>
<% end %>

<h1>Create a ring<h1>

<%= render 'form' %>

app/views/rings/show.html.erb
<p id="notice"><%= notice %></p>
 
<h1>
  <b>Ring: <%= @ring.name %></b>
</h1>
 <h2>Size: <%= @ring.size %> miles</h2>
 <h2>Category: <%= @ring.categories.first.name %></h2>
  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@ring.latitude}%2C#{@ring.longitude}"%>
 <h3>Posts</h3>

<% @ring.posts.each do |post| %>
  <div class ="well">
	<b><%= post.content %></b>
  <h5><br />
    Posted by: <b><%= post.user.name %></b>
  </h5>
  </div>
<% end %>

<%= form_for([@ring, @ring.posts.build]) do |f| %>
  <div class="textarea">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Post" %>
  </div>
<% end %>
 

app/views/static_pages/_ringsessionform.html.erb
<%= form_tag ring_sessions_path do %>

<div class="field">
	<%= hidden_field_tag :latitude %>
	<%= hidden_field_tag :longitude %>
</div>
<br />
<div class="actions">
	<%= submit_tag 'Ring Check' %>
</div>

<% end %>

app/views/static_pages/home.html.erb
<% content_for :javascripts do %>
   <%= javascript_include_tag "geolocation" %>
<% end %>

<div class="center hero-unit">
  <h1>Welcome to Ringtack</h1>

  <h2>
    Make real world communities better.
  </h2>


  <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-large btn-primary" %>


  <%= render 'ringsessionform' %>
</div>